services:
  oracle:
    image: scalified/oracle-database:12.2.0.1-ee
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=dbz 
    restart: unless-stopped

  postgres:
    image: docker.io/bitnami/postgresql:16.3.0
    container_name: postgres
    environment:
      - POSTGRESQL_PASSWORD=postgres123AA

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mssql123AA
    ports:
      - "1433:1433"
    restart: unless-stopped
  dbz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbz
    command: ["python", "src/dbz_oracle_to_mssql_handler.py"]
    # command: ["python", "src/dbz_oracle_to_postgres_handler.py"]
    # command: ["python", "src/dbz_custom_handler.py"]
    # command: ["sleep", "infinity"]
    volumes:
      - ./storage:/app/storage
    environment:
      - ORACLE_HOST=oracle
      - ORACLE_PORT=1521
      - ORACLE_USER=c##dbzuser
      - ORACLE_PASSWORD=dbz
      - ORACLE_DBNAME=ORCLCDB
      - ORACLE_PDB_NAME=ORCLPDB1
      - ORACLE_TABLE_INCLUDE_LIST=C##DBZUSER.CUSTOMERS,C##DBZUSER.CUSTOMERS1,C##DBZUSER.CUSTOMERS2
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres123AA
      - POSTGRESQL_DB=postgres
      - POSTGRESQL_INSERT_BATCH_SIZE=1000
      - MSSQL_HOST=mssql
      - MSSQL_PORT=1433
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=mssql123AA
      - MSSQL_DB=raw_db
      - MSSQL_INSERT_BATCH_SIZE=1000
      - OFFSET_FILE=/app/storage/offsets.dat
      - HISTORY_FILE=/app/storage/history.dat
      - CLEAR_OFFSET_AND_HISTORY_FILE=false